### ISSUE TITLE
Easiest way to get a "total" column

### ISSUE THREAD

**Issue by aghaynes** [arminstroebel/atable#6]
What's the easiest way to get a "total" column including all observations, as well as values split by `group_col`? Running `atable` twice, once with, once without `group_col`? It doesn't look like there's anything else at the moment...
Thanks!

**Comment by arminstroebel** [comment]
No, there nothing implemented at the moment to add a total column while also having group_col. Calling atable twice is possible, and then do some rbinding or cbinding with the results, as you wrote. 

When atable is called with a group_col, the data.frame is splitted by that column and the whole data.frame is not analysed, just its parts. 

I am thinking of something like the addmargins function of the stats package...

cbinding the results of atable of the whole data.frame to the right of the grouped atable results, or between the p-value and the group-columns

**Comment by aghaynes** [comment]
Thanks. That's what I thought. I would add it before the groups (total, group1, group2, ..., stat, p, ...), but that's personal preference...

**Comment by arminstroebel** [comment]
atable Version 0.1.8 now can add a total column to the table via argument add_margins, See the help ?atable for details.

**Comment by aghaynes** [comment]
Super, thanks!
