### ISSUE TITLE
extending and modifying vignettes missing from CRAN version

### ISSUE THREAD

**Issue by aghaynes** [arminstroebel/atable#8]
I just noticed that the extending and modifying vignettes are missing from the CRAN version of the package (I'm pretty sure that they were there in the 1.7 version...)

**Comment by arminstroebel** [comment]
mh. not good. Will add. I think i will also do something about the indent_character. It should be modifiyable, as the other arguments.

**Comment by arminstroebel** [comment]
Version 1.9 is on CRAN with the vignettes. I close this issue.
